on: push

name: Build Random Highway Sign

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      
      - run: yarn install

      - run: yarn run build
        env:
          search_service: ${{ secrets.search_service }}
          search_key: ${{ secrets.search_key }}

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'v'
