on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      
      - run: yarn install

      - run: yarn run build:production
        env:
          SEARCH_SERVICE: ${{ secrets.SEARCH_SERVICE }}
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}

      - uses: chrislennon/action-aws-cli@v1.1
        if: ${{ github.ref == 'refs/heads/gh_action' }}

      - name: Upload S3
        if: ${{ github.ref == 'refs/heads/gh_action' }}
        run: |
            aws s3 sync dist/ s3://random.roadsign.pictures/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate Cache
        if: ${{ github.ref == 'refs/heads/gh_action' }}
        run: |
            aws cloudfront create-invalidation --distribution-id EKWK50GJ6BOOE --paths /index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
