on: push

name: Build Random Highway Sign

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
      
      - run: yarn install

      - run: yarn run build
        env:
          SEARCH_SERVICE: ${{ secrets.SEARCH_SERVICE }}
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          VERSION: "v1.0.0"

  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
      
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        id: versionBump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'v'

      - run: yarn install

      - run: yarn run build
        env:
          VERSION: ${{ steps.versionBump.outputs.newTag }}
          SEARCH_SERVICE: ${{ secrets.SEARCH_SERVICE }}
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      - name: Upload S3
        run: |
            aws s3 sync dist/ s3://random.roadsign.pictures/

      - name: Invalidate Cache
        run: |
            aws cloudfront create-invalidation --distribution-id EKWK50GJ6BOOE --paths /index.html
