on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      
      - run: yarn install

      - run: yarn run build
        env:
          SEARCH_SERVICE: ${{ secrets.SEARCH_SERVICE }}
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      - name: Upload S3
        if: ${{ github.ref == 'refs/heads/gh_action' }}
        run: |
            aws s3 sync --debug dist/ s3://random.roadsign.pictures/

      - name: Invalidate Cache
        if: ${{ github.ref == 'refs/heads/gh_action' }}
        run: |
            aws cloudfront create-invalidation --distribution-id EKWK50GJ6BOOE --paths /index.html