on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      
      - run: yarn install

      - run: yarn run build:production
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}

      - uses: chrislennon/action-aws-cli@v1.1

      - name: Upload S3
        run: |
            aws s3 sync dist/ s3://random.roadsign.pictures/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate Cache
        run: |
            aws cloudfront create-invalidation --distribution-id E32QZ8EDKNQ6AF --paths /index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
