on:
  release:
    types: [released]

name: Deploy Random Highway Sign

jobs:
  build:
    name: Deploy Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      
      - run: yarn install

      - run: yarn run build
        env:
          SEARCH_SERVICE: ${{ secrets.SEARCH_SERVICE }}
          SEARCH_KEY: ${{ secrets.SEARCH_KEY }}

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      - name: Upload S3
        run: |
            aws s3 sync dist/ s3://random.roadsign.pictures/

      - name: Invalidate Cache
        run: |
            aws cloudfront create-invalidation --distribution-id EKWK50GJ6BOOE --paths /index.html